- README.md
- circle.yml
FYI: I'll just be merging PRs myself for this repo while we're getting started.
I'm gonna be making changes in PRs so I can have Hound review style violations.
> Create CircleCI config

- db/migrate/20161119154945_add_streak_key_indexes.rb
- db/schema.rb
Speeds up querying in the Streak sync logic.
> Add indexes to streak_key fields

- app/models/club.rb
- app/models/concerns/geocodeable.rb
- app/models/leader.rb
- spec/factories/leaders.rb
- spec/models/club_spec.rb
- spec/models/leader_spec.rb
- spec/support/shared_examples/geocodeable.rb
> Only geocode on address change

- config/initializers/cors.rb
- spec/requests/cors_spec.rb
> Fix CSRF vulnerability.

- app/models/hackbot/conversations/check_in.rb
Thanks for the suggestion @klipspringr!
> Make minor wording change to check-in conversation

- app/models/hackbot/conversations/mention.rb
> Fix hackbot triggering itself

- app/models/hackbot/conversations/gifs.rb
- app/models/hackbot/dispatcher.rb
- circle.yml
- config/secrets.yml
- lib/giphy_client.rb
This is the beginning of some **fun** *activities* in Hackbot.
It's pretty simple, and allows Hackbot to respond people with gifs as they request them 💃
> Hackbot giphy

- app/models/hackbot/conversations/check_in.rb
> Add separate response if no notes are provided

- app/models/hackbot/conversation.rb
- app/models/hackbot/conversations/check_in.rb
- app/models/hackbot/conversations/gifs.rb
- app/models/hackbot/conversations/help.rb
- app/models/hackbot/conversations/set_poc.rb
- app/services/copy_service.rb
- lib/data/copy/check_in.yml
- lib/data/copy/gifs.yml
- lib/data/copy/help.yml
- lib/data/copy/set_poc.yml
Hackbot has gotten to the point where we need to start separating copy from implementation. This is the beginning of that. I'm tired. I'll write a prettier description soon. I think?
Fixes #84
@MaxWofford: Would you be interested in writing some creative copy for Hackbot?
> Hackbot copy system

- app/models/hackbot/conversation.rb
- app/models/hackbot/conversations/gifs.rb
- app/models/hackbot/conversations/help.rb
> Fix Hackbot case sensativity

- Dockerfile
- Gemfile
- Gemfile.lock
- app/controllers/v1/hackbot/webhook_controller.rb
- app/jobs/handle_slack_event_job.rb
- app/models/hackbot/conversation.rb
- app/models/hackbot/conversations/channel.rb
- app/models/hackbot/conversations/check_in.rb
- app/models/hackbot/conversations/stats.rb
- app/models/hackbot/dispatcher.rb
- app/services/charts_service.rb
- app/services/copy_service.rb
- app/services/stats_service.rb
- lib/charts.rb
- lib/data/copy/stats.yml
- lib/slack_client/files.rb
This PR adds a nice little graph to the end of check ins which shows your attendance.
I'd really appreciate it if @MaxWofford could do some styling on the graph.
Fix #82 and a bug where you can have the same event being processed in two different threads concurrently.
Issues:
- Something is really wrong with Rails and separate threads...
> Add attendance graphs to Hackbot check ins

- app/jobs/leader_check_in_job.rb
- app/models/hackbot/conversations/check_in.rb
Theses changes should have been bundled with https://github.com/hackclub/api/pull/116
> New check ins close old check in conversations

- lib/data/copy/check_in.yml
- lib/data/copy/gifs.yml
- lib/data/copy/help.yml
- lib/data/copy/stats.yml
This includes a bunch of changes to copy to turn Hackbot into GLaDOS.
It's still unfinished: DO NOT MERGE.
> GLaDOS Copy

- app/jobs/schedule_leader_check_ins_job.rb
Merging this because it is time sensitive and I'm the only one currently online.
> Fix ScheduleLeaderCheckInsJob for nil clubs

- README.md
- app/models/hackbot/interaction.rb
- app/models/hackbot/interactions/concerns/mirrorable.rb
- app/models/hackbot/interactions/gifs.rb
- app/models/hackbot/interactions/text_conversation.rb
- circle.yml
- config/secrets.yml
- lib/data/copy/concerns/mirrorable.yml
- lib/data/copy/gifs.yml
- lib/slack_client.rb
- lib/slack_client/channels.rb
- lib/slack_client/groups.rb
- lib/slack_client/im.rb
- lib/slack_client/mpim.rb
This PR, as evident from the title, makes a few improvements to Hackbot.
1. One minor copy fix (a620c97)
2. One minor bug fix (3095bec)
3. One minor lawsuit avoided (3fa2e67)
4. One UX improvement (9513a4a)
5. One internal tool implemented (135d0be)
6. One CI made happy (b038285)
> Make various Hackbot improvements

- app/models/hackbot/interactions/concerns/mirrorable.rb
Hopefully pretty self-explanatory.
> Color mirrored messages by interaction id

- lib/data/copy/check_in.yml
Currently watching the check ins going past and fixing up some problems people are having.
> Update check in copy

- app/jobs/schedule_leader_check_ins_job.rb
Last week we changed the Club pipeline to have different stages where a club can still be active. Our current ScheduleLeaderCheckInJob assumes that active clubs are only in the active stage. Hence, this fix.
> Fix ScheduleLeaderCheckInsJob not scheduling all check ins

- app/jobs/close_check_ins_job.rb
- app/jobs/schedule_leader_check_ins_job.rb
- lib/data/copy/jobs/close_check_ins_job.yml
Since we've decided to explicitly close check ins at 8am on Monday morning, we need to separate the logic out of the current `LeaderCheckInJob` which only closes check ins just before it schedules a new one.
**DO NOT MERGE**
> Add CloseCheckInsJob

- app/models/hackbot/interactions/welcome.rb
This conversation was throwing an error because the name parameter was not set.
> Fix welcome conversation

- app/controllers/v1/hackbot/webhooks_controller.rb
This makes Slack disable buttons for 2.5 seconds after they're clicked.
> Delay button HTTP request responses by 2.5 seconds

- app/models/hackbot/interactions/check_in.rb
Reverts hackclub/api#176
Merged the wrong PR! Whoops.
> Revert "Remove invalid case in check-ins"

- app/models/hackbot/interactions/check_in.rb
- lib/data/copy/check_in.yml
This PR adds a button to Hackbots initial message with a suggestion of what day of the week your club would have met.
First message:
After clicking 'Yes, on Friday'
> Hackbot check in remember last meeting day

- app/jobs/schedule_leader_check_ins_job.rb
- app/jobs/update_from_streak_job.rb
- app/models/club.rb
- app/models/concerns/streakable.rb
- app/models/leader.rb
- app/models/letter.rb
- db/migrate/20170417231434_add_stage_to_streakables.rb
- db/schema.rb
- lib/hc_faker.rb
- spec/factories/clubs.rb
- spec/models/club_spec.rb
- spec/requests/v1/clubs_spec.rb
- spec/support/shared_examples/streakable.rb
This PR adds support for the syncing of Streak stages.
~Currently WIP because I haven't changed `ScheduleLeaderCheckInsJob` to use it yet.~ Done 17/04/17 6:36 PM PDT.
~Currently trying to fix the tests, then this will be good to go.~ 18/04/17 9:00PM PDT
Ready to review!
> Add syncing of Streak stages

- Procfile
- app/jobs/close_check_ins_job.rb
- app/jobs/follow_up_if_needed_job.rb
- app/jobs/handle_slack_event_job.rb
- app/jobs/schedule_leader_check_ins_job.rb
This introduces a non-default job queue: 'slack_events'.
> Add job queues

- app/models/hackbot/interactions/concerns/leader_associable.rb
- app/models/hackbot/interactions/text_conversation.rb
- app/services/check_in_report_service.rb
- lib/tasks/export/check_ins.rake
This PR adds some scripts which make my job on Monday morning of generating reports from the weekend's check ins super easy.
~Think of the current state as a WIP. I'm pushing this now in the hope of a review, and will come back in the morning after some sleep to finish it off.~ Ready for review as of 14/04/17
> Hackbot check in reports

- app/models/hackbot/interactions/set_poc.rb
- lib/data/copy/set_poc.yml
I... felt the need to do this for some reason.
> Add statements of positivity to the set-poc command

- app/models/club.rb
- app/models/hackbot/interactions/check_in.rb
- db/migrate/20170505071139_add_activation_date_to_club.rb
- db/schema.rb
- lib/data/copy/check_in.yml
This adds the dormant conversation flow to Hackbot.
Currently working on adding the 'Start date' field to Streak/DB.
> Add dormant conversation flow

- app/models/hackbot/dispatcher.rb
- app/models/hackbot/interactions/notify.rb
- lib/data/copy/notify.yml
This PR adds the long-awaited 'hackbot notify' command which was requested by @cravend many moons ago.
> Add hackbot notify command
