- app/jobs/update_from_streak_job.rb
We've hit the point where Streak has started throwing 500s and 503s when calling GET /v1/boxes -- probably a result of having too many boxes.
This change makes it so our sync logic retrieves pipelines one at a time, hopefully fixing the issue with getting errors from their API.
> GET each Streak pipeline individually when syncing

- app/models/concerns/streakable.rb
- lib/streak_client.rb
- lib/streak_client/box.rb
- lib/tasks/outreach/teacher_emails/associate_teachers.rake
- spec/support/shared_examples/streakable.rb
This change makes it so we can pass params with snake_case keys into
StreakClient and have them transformed for Streak's API.
> Camelize params passed into StreakClient

- README.md
- app/controllers/v1/hackbot/auth_controller.rb
- app/controllers/v1/hackbot/webhook_controller.rb
- app/models/hackbot.rb
- app/models/hackbot/conversation.rb
- app/models/hackbot/conversations/attendance.rb
- app/models/hackbot/conversations/channel.rb
- app/models/hackbot/conversations/mention.rb
- app/models/hackbot/dispatcher.rb
- app/models/hackbot/team.rb
- circle.yml
- config/routes.rb
- config/secrets.yml
- db/migrate/20161231005311_create_hackbot_teams.rb
- db/migrate/20170101004638_create_hackbot_conversations.rb
- db/schema.rb
- lib/slack_client.rb
- lib/slack_client/chat.rb
- lib/slack_client/oauth.rb
- spec/models/hackbot/conversation_spec.rb
- spec/models/hackbot/team_spec.rb
This pull request creates the initial version of `hackbot`, our friendly bot that we're going to use to collect attendance from clubs in 2017.
@paked: I'm going to merge this myself for now because you're not yet full-time on this project, but would love any feedback you have on how to improve this – I'm considering changing the "abstract" model for interactions from `Conversation` to `Interaction` and then having `Conversation` as a subclass that only deals with messages and I know there are many other things that can be improved (tests being one of them).
> Create initial version of hackbot

- app/models/check_in.rb
- app/models/hackbot/conversations/check_in.rb
- spec/models/check_in_spec.rb
`notes` was a required field and would be `nil` when the user didn't have anything they wanted to send us.
> Fix bug preventing creation of CheckIn instances

- app/models/hackbot/conversation.rb
- app/models/hackbot/conversations/help.rb
- app/models/hackbot/conversations/mention.rb
This PR fixes the issue where people mention `help` in casual conversation, and hackbot subsequently decides it is it's queue to spam the channel with a quick bio. It's rather insensitive.
As part of this I've added a new class method, `mentions_name?` to `Hackbot::Conversation`, I've noticed that the mention code is starting to be repeated (and I imagine it will continue to in the future).
> Fix help triggering too often

- app/models/hackbot/conversations/check_in.rb
In our last batch of Hackbot check ins, we had 74 clubs who did not meet. This is a problem, but the currently truly-horrifying-horror-movie-situation we have right now is that we have **no** idea why these clubs didn't meet.
This PR fixes that. When a leader states they haven't had a meeting this week, they'll be prompted for why this was.
> Add question asking why a meeting didn't happen

- app/jobs/leader_check_ins_job.rb
This PR adds the ability for us to explicitly specify which usernames to send leader check ins to.
> Add specific usernames option

- Dockerfile
This PR closes #73.
This allows you to connect to the development database using the Postgres CLI client and use the Rails command `rails dbconsole` to launch the Postgres REPL with the local databases.
> Add postgresql-client to Dockerfile

- app/jobs/follow_up_if_needed_job.rb
- app/jobs/leader_check_ins_job.rb
- app/models/hackbot/conversations/check_in.rb
- app/models/hackbot/conversations/follow_up.rb
- app/models/hackbot/conversations/followup.rb
- lib/data/copy/check_in.yml
Closes #87
This PR adds automated follow-ups to Hackbot, in the form of a delayed job.
In order to test, you probably want to change [this line](https://github.com/hackclub/api/compare/hackbot-follow-ups?expand=1#diff-10e8a2297a6c1b210e2f9f004785731cR171) to be a more test-reasonable number. I usually use `10.seconds`.
Cases that need to be tested:
- Not responding to Hackbot will trigger a message
- Responding to Hackbot after it has pinged you will stop it from continuing to ping you.
- Hackbot correctly follows up after the correct messages (ie. if the conversation is finished, there is no need to follow-up)
- If the conversation is killed before it is finished, Hackbot will not continue following up.
- Hackbot is sending the correct pings in the correct order.
- Hackbot stops pinging …
> Hackbot follow-ups

- app/services/copy_service.rb
My explanation from Slack with @MaxWofford.
> figured out the problem
> 
> [1:56]  
> some of our clubs have `\r` appended to the back of their names
> 
> [1:56]  
> when this is rendered
> 
> [1:56]  
> it takes the valid [yaml]
> 
> [1:57]  
>  ```
> key: <%= info[:value] %> by bob
> key2: potato
> ```
> (edited)
> 
> [1:57]  
> and turns it into
> 
> [1:57]  
> (with `value=hello\r`)
> 
> [1:58]  
>  ```key: hello
>  by bob
> key2: potato
> ```
> (edited)
> [which is not valid yaml]
TLDR: Some of our club names in the database have extraneous newlines post-pended to them. This was fucking with YAML, to fix this I've changed the order in which we use ERB and YAML. (Used to be `ERB to YAML`, now is `YAML to ERB`)
> Fix copy service bug

- app/jobs/leader_check_ins_job.rb
We kind of left the point of contact system in a weird place last week, everything was implemented into the database and Streak but no changes were made to accomodate those in `LeaderCheckInsJob`.
This is those changes.
**Note: In order to properly test the code you will have to move a test leader into the `ACTIVE` stage for a short period of time.**
**Functionality**
- Streak keys can be provided through `LeaderCheckInsJob.perform_now keys` parameter.
- Only leaders in the active stage will be pinged during a check in.
**Things to test!**
- Leaders will be correctly classified as active or not active based off of their position in the Streak Club Leaders pipeline
- The job only pings leaders which are active
- If a list of Streak keys is provided as a parameter, they will be used instead …
> Fix POC system

- README.md
- app/models/hackbot/conversations/check_in.rb
- circle.yml
- config/secrets.yml
This PR closes #88.
Things to test:
- Tasks get assigned to the right person
- Tasks are generated when there are notes outputted from a conversation. (1. if there wasn't a meeting. 2. if there was a meeting)
I've already configured our production environment to put @kyleemile as the default assignee.
> Add Streak tasks which are generated from notes

- app/jobs/schedule_leader_check_ins_job.rb
This PR adds a flag to schedule all check ins to run immediately, instead of trying to schedule them.
It's useful in cases of emergencies or when we don't know if the Google Maps API key we're using has TimeZones enabled.
> Add flag to not use timezones and send check ins immediately

- app/models/hackbot/conversations/gifs.rb
- app/models/hackbot/conversations/help.rb
This PR fixes our various conversations [throwing errors](https://sentry.io/hack-club/api/issues/230714483/) when they have to process events that aren't of type `message`.
> Fix errors from conversations responding to non-messages

- lib/dot_tech_client.rb
This PR fixes a typo that was preventing submission of .TECH domain requests (thanks to @mj66, @lachlanjc, and the many others that caught this).
Once this is merged, we'll have to retroactively submit existing requests. I can take care of that.
> Fix typo preventing submission of .TECH domain requests

- app/models/hackbot/interactions/stats.rb
- app/services/stats_service.rb
- lib/data/copy/stats.yml
Closes #145.
Tests:
- Slack user who is not a leader gets correct copy (and no errors)
- Leader who has not had 3 check ins gets correct copy (and no errors)
- A Leader who has had more than 3 check ins gets correct copy and a render of their stats
> Fix stats command not handling invalid input correctly

- docker-compose.yml
This PR starts `rails jobs:work` when running `docker-compose up`.
> Start job worker with `docker-compose up`

- app/models/hackbot/interactions/check_in.rb
- lib/data/copy/check_in.yml
This PR adds a new conversation flow for check ins if the leader says they did not have a club meeting.
Here's the spec sheet I got from @kyleemile. I've changed the copy around a bit to make it better.
```
Hackbot: Hi, time for check-in's, did you have a meeting this last week? 
User: No
Hackbot: How unfortunate, why wasn't there a meeting?
User: [explanation]
Hackbot: Are you planning on having club meetings in the future?
User: [y/n]
If NO: 
Hackbot: Aww, that's sad to hear. I'll be sure to let the Hack Club Team know.
IF YES: 
Hackbot: Sweet, is there anything that the Hack Club team can be helpful with? 
User: [answer]
Hackbot: Got it. That's all for now. 
```
Tests:
- Correct copy is used in all the flow
- No meeting reason is recorded in the data object (key: `no_meeting_reason`)
- …
> Add new no meeting conversation flow

- app/models/hackbot/dispatcher.rb
- app/models/hackbot/interactions/check_in.rb
Currently if we run check ins, Hackbot will not respond to any messages which should be part of that conversation. This is bad.
> Add check ins back into the dispatcher

- app/models/hackbot/interaction.rb
- app/models/hackbot/team.rb
- app/services/copy_service.rb
- lib/data/copy/check_in.yml
- lib/data/copy/concerns/mirrorable.yml
- lib/data/copy/dice_roll.yml
- lib/data/copy/help.yml
- lib/data/copy/set_poc.yml
- lib/data/copy/stats.yml
- lib/data/copy/welcome.yml
TLDR:
Using `{team: team, event: event, first_name: 'Harrison'}`
```yml
message: Helllo! I am <@<%= info[:team].bot_user_id %>. This events timestamp is <%= info[:event] %>. The custom parameter you passed in is <%= info[:first_name] %>.
```
Using `{first_name: 'Harrison'}`. (`team` and `event` are passed in at the `Hackbot::Interaction` level)
```yml
message: Hello! I am <%= team.bot_mention %>. This events timestamp is <%= event[:ts] %>. The custom parameter you passed in is <%= first_name %>.
```
This PR refactors Hackbot's copy system to be a bit nicer to play with.
- We now have some nice default values in available in the copy scope. You're able to access `event` and `team` without passing them in explicitly.
- Instead of accessing values through a hash, you access them directly. …
> Refactor Hackbot copy system

- Procfile
This change introduces a Procfile, which sets up 3 Heroku workers -- having the
three workers defined in the Procfile instead of through Heroku's config allows
us to use multiple hobby dynos for multiple workers, keeping costs down.
> Create Procfile w/ three workers

- README.md
This PR adds `GIPHY_API_KEY` to the list of required environment variables.
> Document requirement of Giphy's API key

- app/models/hackbot/interactions/check_in.rb
- lib/data/copy/check_in.yml
This PR adds a hard limit on how big the attendance of a club meeting can be.
I chose the number 8 billion because we are not projected to even have a population that size (let everyone having access to the internet) until 2025.
If it's more appropriate, we could use `2147483647` which is the max size of a PostgreSQL integer? I just think that 8 billion is much more human.
> Add a limit on meeting sizes

- app/models/hackbot/interactions/check_in.rb
This PR makes a super simple UX change that puts the suggested meeting day of week as the first button in the list.
Before:
```
[ Yes ], [ Yes, on Thursday ], [ No ]
```
Now:
```
[ Yes, on Thursday ], [ Yes ], [ No ]
```
Just spoke with a leader about how they'd improve check-ins and this is what they suggested. They accidentally clicked "Yes" when they meant to click "Yes, on Thursday" and all hell broke loose after they quickly tried to click "Yes,  on Thursday" to correct themselves (so some extra events were sent to Hackbot and it tried to process them).
> Put the suggested meeting date button first, if available

- app/controllers/v1/hackbot/webhooks_controller.rb
Slack HTML escapes the `>`, `<`, and `&` characters. This was causing unexpected behavior with `hackbot sql`, where queries like `SELECT id, name FROM leaders WHERE created_at > current_date - interval '7 days'` weren't working because Slack would replace `>` with `&gt;`.
With this change, `event[:text]` will include the text as the user typed it (except for when the user @mentions someone or sends a link).
> Unescape HTML escaped event text

- bin/delayed_job
This change removes `bin/delayed_job` because we're using `rails jobs:work` to invoke our worker instead. Occam's Razor, yo.
If we wanted to use `bin/delayed_job`, we'd have to install the `daemons` gem anyways. See https://github.com/collectiveidea/delayed_job#running-jobs.
> Remove unused bin/delayed_job

- app/models/hackbot/dispatcher.rb
- app/models/hackbot/helpers.rb
- app/models/hackbot/interactions/admin_command.rb
- app/models/hackbot/interactions/lookup.rb
- app/models/hackbot/interactions/set_poc.rb
- app/models/hackbot/interactions/sql.rb
- app/models/hackbot/slack_interaction.rb
- app/services/club_stats_service.rb
- app/services/copy_service.rb
- lib/data/copy/admin_command.yml
- lib/data/copy/lookup.yml
- lib/data/copy/set_poc.yml
- lib/data/copy/sql.yml
These changes do three things:
1. Allow you to get objects outside of the copy system (see [here](https://github.com/hackclub/api/blob/6cdb2bf20a3b5c6dd7ff1d39175286c8528cf8b4/lib/data/copy/lookup.yml#L3-L15) for an example, it's surprisingly nice for Slack messages that include actions). If this is merged, our copy system is turning more into a view system. Might be worth more discussion around making it a view system at some point?
2. Allow you to look up a leader and details on their clubs with `hackbot lookup @slack_username`. Surprisingly nice for getting context on who people are, I've been playing around with it all day and been pleasantly surprised.
3. Refactor all this admin logic that's been being implemented into a class called `AdminCommand`. Want a command to only work for …
> Implement `hackbot lookup` command

- app/models/hackbot/interactions/command.rb
- lib/data/copy/help.yml
This change makes it so you can PM Hackbot commands directly without mentioning its username.
Before:
After:
> Don't require username to trigger commands in PMs

- app/models/hackbot/interactions/admin_command.rb
Fixes the issue @ItsDaGeek found in https://hackclub.slack.com/files/jrc/F507T35A9/pasted_image_at_2017_04_17_10_02_am.png.
> Set state to :finish when denying an interaction to a non-admin

- lib/streak_client/box.rb
This PR changes the way in which `StreakClient::Box.all_in_pipeline` retrieves it's boxes. Previously it pulled down the entire pipeline at once through the v1 API, which *sometimes caused 500 errors* and was very slow. Now, we use pagination (ie. the v2 API).
This should be good to merge as it is, and not effect the performance of our application too much – but I do want to consider caching this function just to make everything as quick as possible.
If we do decide to cache, what would this look like? Caching the individual network requests seems like a bad idea prone to error. Does that mean we just cache at a function level?
Would love your thoughts @MaxWofford.
> Use pagination for StreakClient::Box.all_in_pipeline

- app/controllers/v1/leaders_controller.rb
- app/models/hackbot/interactions/set_poc.rb
- app/services/copy_service.rb
- lib/data/copy/set_poc.yml
- spec/requests/v1/leaders_spec.rb
Last week we had a meeting which decreed that letters shall only be
created for POCs to ensure that we can not fall behind and create a
massive backlog.
> Update the way we handle letter box creation
